---
- hosts: all
  tasks:
  - name: debug system info
    debug:
      msg: "Remote host system information: {{ansible_facts}}"

  - name: get the rpm package facts
    package_facts:
      manager: rpm

  - name: list package info
    debug: var=ansible_facts.packages

